# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

# CYRA-550 — la copertura si avvia QUI, come prima riga eseguita di tutto il run.
#
# Due ragioni, e nessuna delle due è di stile. Da simplecov 1.0 `.simplecov` è un file di sola
# configurazione: lo `SimpleCov.start` che stava lì dentro è deprecato e in una prossima versione
# smetterà di avviare il tracking senza che nessuno se ne accorga. E il tracking deve cominciare
# prima di qualunque codice applicativo: `rails_helper` non basta, perché gli spec che non hanno
# bisogno di Rails non ci passano mai — un run fatto solo di quelli non misurava niente, non
# stampava nessun rapporto e usciva 0 anche col gate acceso, cioè diceva "verificato" senza aver
# verificato.
#
# Questo file è il primo che rspec carica (`.rspec` contiene `--require spec_helper`), quindi è il
# punto giusto. Costa zero quando la copertura è spenta: la politica decide prima di caricare
# qualsiasi gemma. Vedi lib/simplecov_configuration.rb.
require_relative "../lib/simplecov_configuration"
SimplecovConfiguration.start!

# CYRA-711 — dopo l'avvio della copertura, così le sue righe sono misurate come quelle di
# qualunque altro file di lib/.
require_relative "../lib/slowest_examples_policy"

RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # CYRA-551 — l'esito di ogni esempio resta scritto, così `--only-failures` e `--next-failure`
  # hanno qualcosa da leggere: chi insegue un rosso rilancia i tre esempi rossi, non i quindicimila.
  # Il nome porta il numero del processo perché la suite parallela locale ne fa girare otto insieme
  # e su un file solo si sovrascriverebbero a vicenda (parallel_tests lascia il primo a vuoto).
  config.example_status_persistence_file_path = "tmp/rspec_examples#{ENV["TEST_ENV_NUMBER"]}.txt"

  # CYRA-711 — nei controlli automatici, in fondo al run, le dieci prove che si prendono più tempo.
  # La suite dura quanto il suo gruppo più lento e dentro un gruppo il tempo se lo prendono poche
  # prove: senza la classifica, ottimizzare significa indovinare. In locale resta spenta (vedi
  # SlowestExamplesPolicy) perché chi insegue un rosso rilancia tre esempi e non vuole dieci righe
  # di tempi a ogni giro.
  config.profile_examples = SlowestExamplesPolicy.count_for

# The settings below are suggested to provide a good initial experience
# with RSpec, but feel free to customize to your heart's content.
=begin
  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When nothing
  # is tagged with `:focus`, all examples get run. RSpec also provides
  # aliases for `it`, `describe`, and `context` that include `:focus`
  # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  # https://rspec.info/features/3-12/rspec-core/configuration/zero-monkey-patching-mode/
  config.disable_monkey_patching!

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = "doc"
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed
=end
end
